### ISSUE TITLE
Version 0.18.6 crashed on Ubuntu 22.04

### ISSUE THREAD

**Issue by xia0pin9** [gravitl/netclient#363]
I am trying to install netclient on a Ubuntu 22.04 VPS, the command crashed with the following error:
```
root@linux:~# netclient version
[netclient] 2023-04-23 07:53:01 setting OS
[netclient] 2023-04-23 07:53:01 setting version
[netclient] 2023-04-23 07:53:01 setting netclient hostid
[netclient] 2023-04-23 07:53:01 setting name
[netclient] 2023-04-23 07:53:01 setting macAddress
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gravitl/netclient/config.CheckConfig()
	/home/runner/work/netclient/netclient/config/config.go:472 +0x12bf
github.com/gravitl/netclient/config.InitConfig(0xc0000c8340?)
	/home/runner/work/netclient/netclient/config/config.go:423 +0x70
github.com/gravitl/netclient/cmd.initConfig()
	/home/runner/work/netclient/netclient/cmd/root.go:53 +0x4f
github.com/spf13/cobra.(*Command).preRun(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:970
github.com/spf13/cobra.(*Command).execute(0x10f90e0, {0x1137e00, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:900 +0x563
github.com/spf13/cobra.(*Command).ExecuteC(0x10f8840)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/gravitl/netclient/cmd.Execute()
	/home/runner/work/netclient/netclient/cmd/root.go:31 +0x25
main.main()
	/home/runner/work/netclient/netclient/main.go:27 +0x85
```
Host env and installed package version:
```
root@linux:~# dpkg -l | grep netclient
ii  netclient                       0.18.6-0                                               amd64        netclient daemon - a platform for modern, blazing fast wireguard virtual networks
root@linux:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

**Comment by mattkasun** [comment]
the trace indicates that your machine does not have a macAddress on its primary interface;  which is highly doubtful. 

Are you still seeing this issue.
