### ISSUE TITLE
Unable to join network from OpenVZ on version 0.20.0

### ISSUE THREAD

**Issue by rinlabs** [gravitl/netclient#409]
**What Happened?**
Trying to join a network or running a netclient command from a OpenVZ VPS yields the following error:

```
root@01-lim:~# sudo netclient version
[netclient] 2023-05-19 06:02:20 setting OS 
[netclient] 2023-05-19 06:02:20 setting version 
[netclient] 2023-05-19 06:02:20 setting netclient hostid 
[netclient] 2023-05-19 06:02:20 setting name 
[netclient] 2023-05-19 06:02:20 setting macAddress 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gravitl/netclient/config.CheckConfig()
        /home/mkasun/netclient/config/config.go:489 +0x10ff
github.com/gravitl/netclient/config.InitConfig(0xc0000d21a0?)
        /home/mkasun/netclient/config/config.go:437 +0x70
github.com/gravitl/netclient/cmd.initConfig()
        /home/mkasun/netclient/cmd/root.go:53 +0x4f
github.com/spf13/cobra.(*Command).preRun(...)
        /home/mkasun/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:970
github.com/spf13/cobra.(*Command).execute(0x13de620, {0x141eee0, 0x0, 0x0})
        /home/mkasun/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:900 +0x563
github.com/spf13/cobra.(*Command).ExecuteC(0x13ddd80)
        /home/mkasun/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/mkasun/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/gravitl/netclient/cmd.Execute()
        /home/mkasun/netclient/cmd/root.go:31 +0x25
main.main()
        /home/mkasun/netclient/main.go:18 +0x4a
``` 

I suspect this issue is caused by the primary interface (venet0) not having a MAC Address.

```
root@01-lim:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/void 
    inet 127.0.0.1/32 scope host venet0
       valid_lft forever preferred_lft forever
    inet 10.X.X.X/32 brd 10.X.X.X scope global venet0:0
       valid_lft forever preferred_lft forever
    inet6 2001:X:X:X:X:X/128 scope global 
       valid_lft forever preferred_lft forever
3: wg0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1420 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet 10.7.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
    inet6 fddd:X:X:X:X:X/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::X:X:X:X/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever
```

**Comment by mattkasun** [comment]
netclient requires a mac address for proper functioning
